name: Deploy Laravel to Namecheap Backend

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: 23.187.248.15
        username: backend@wizmeek.com
        password: eFNZuakAk6P
        local-dir: ./api/
        server-dir: /
